# Doing the following jobs:
# 1. Find clusters using resolution 0-2 (0.1 per step)
# 2. Run UMAP (umap)
# 3. Add Cell Ranger projection file (tsne_cr)

RunUMAP <- function(
    object, cells.use = NULL, dims.use = 1:5, reduction.use = "pca",
    genes.use = NULL, assay.use = "RNA", max.dim = 2L,
    reduction.name = "umap", reduction.key = "UMAP", n_neighbors = 30L,
    min_dist = 0.3, metric = "correlation", seed.use = 42, ...)
{
    require('reticulate')
    require('Seurat')
    use_virtualenv(file.path(here::here(), 'venv'), required = TRUE)

    if (!py_module_available(module = "umap")) {
        stop("Cannot find UMAP, please install through pip (e.g. pip install umap-learn).")
    }
    if (!is.null(x = seed.use)) {
        set.seed(seed = seed.use)
        py_set_seed(seed = seed.use)
    }
    SetIfNull <- function(x, default)
    {
        if (is.null(x = x)) {
            return(default)
        }
        else {
            return(x)
        }
    }
    SetCalcParams <- function(object, calculation, time = TRUE, ...)
    {
        object@calc.params[calculation] <- list(...)
        object@calc.params[[calculation]]$object <- NULL
        object@calc.params[[calculation]]$object2 <- NULL
        if (time) {
            object@calc.params[[calculation]]$time <- Sys.time()
        }
        return(object)
    }
    cells.use <- SetIfNull(x = cells.use, default = colnames(x = object@data))
    if (is.null(x = genes.use)) {
        dim.code <- GetDimReduction(
            object = object,
            reduction.type = reduction.use,
            slot = "key"
        )
        dim.codes <- paste0(dim.code, dims.use)
        data.use <- GetDimReduction(
            object = object,
            reduction.type = reduction.use,
            slot = "cell.embeddings"
        )
        data.use <- data.use[cells.use, dim.codes, drop = FALSE]
    } else {
        data.use <- GetAssayData(
            object = object,
            assay.type = assay.use,
            slot = "scale.data"
        )
        genes.use <- intersect(x = genes.use, y = rownames(x = data.use))
        if (!length(x = genes.use)) {
            stop("No genes found in the scale.data slot of assay ",
                 assay.use)
        }
        data.use <- data.use[genes.use, cells.use, drop = FALSE]
        data.use <- t(x = data.use)
    }
    parameters.to.store <- as.list(x = environment(), all = TRUE)[names(formals("RunUMAP"))]
    object <- SetCalcParams(
        object = object,
        calculation = "RunUMAP",
        ... = parameters.to.store
    )
    umap_import <- import("umap")
    umap <- umap_import$UMAP(
        n_neighbors = as.integer(x = n_neighbors),
        n_components = as.integer(x = max.dim),
        metric = metric,
        min_dist = min_dist
    )
    umap_output <- umap$fit_transform(as.matrix(x = data.use))
    colnames(x = umap_output) <- paste0(reduction.key, 1:ncol(x = umap_output))
    rownames(x = umap_output) <- cells.use
    object <- SetDimReduction(
        object = object,
        reduction.type = reduction.name,
        slot = "cell.embeddings",
        new.data = as.matrix(x = umap_output)
    )
    object <- SetDimReduction(
        object = object,
        reduction.type = reduction.name,
        slot = "key",
        new.data = reduction.key
    )
    return(object)
}

# Add t-SNE projection file generated by Cell Ranger to Seurat object
AddProjection <- function(object, projection_file) {
    stopifnot(class(object) == "seurat")
    require('Seurat')
    # t-SNE of Cell Ranger
    reduction.name = 'tsne_cr'

    projection <- as.matrix(read.csv(projection_file, row.names = 1))
    colnames(projection) <- c('tSNE_1', 'tSNE_2')
    rownames(projection) <- sub('-[0-9]+$', '', rownames(projection))

    stopifnot(all(object@cell.names %in% rownames(projection)))
    projection <- projection[object@cell.names,]

    object <- SetDimReduction(object = object, reduction.type = reduction.name, slot = 'cell.embeddings', new.data = projection)
    object <- SetDimReduction(object = object, reduction.type = reduction.name, slot = 'key', new.data = 'tSNE_')
    return(object)
}

update_seurat_obj <- function(
    seurat.file,
    projection.file = NA_character_,
    dims.use = 1:12
) {
    require('Seurat')
    require('tidyverse')

    object <- read_rds(seurat.file)
    stopifnot(class(object) == "seurat")

    if (length(dims.use) == 1) {
        dims.use = 1:dims.use
    }

    object@meta.data <- object@meta.data[,!str_detect(colnames(cb@meta.data), '^res')]
    object <- FindClusters(
        object = object,
        dims.use = dims.use,
        resolution = seq(from = 0, to = 2, by = 0.1)
    )
    object <- SetAllIdent(object, id = 'res.0.8')

    object <- RunUMAP(object, dims.use = dims.use)
    if (!is.na(projection.file)) {
        object <- AddProjection(object, projection.file)
    }
    return(object)
}

library(jsonlite)
library(glue)
resource.list <- read_json('shiny/data/resource_list.json')
walk2(
    map_chr(resource.list, ~.$label),
    map_dbl(resource.list, ~.$dims.use),
    function(sample, dims) {
        print(sample)
        object <- update_seurat_obj(
            seurat.file = glue('shiny/data.bak/{sample}/{sample}.rds'),
            projection.file = glue('shiny/data.bak/{sample}/projection.csv'),
            dims.use = 1:dims
        )
        dir.create(glue('shiny/data/{sample}'), showWarnings = FALSE)
        write_rds(object, glue('shiny/data/{sample}/{sample}.rds'),
                  compress = 'gz')
})

for (resource in resource.list) {
    if (!is.null(resource$subset)) {
        sample.parent <- resource$label
        print(resource$description)
        for (resource.subset in resource$subset) {
            sample <- resource.subset$label
            print(resource.subset$description)
            dims <- resource$dims.use
            object <- update_seurat_obj(
                seurat.file = glue('shiny/data.bak/{sample}/{sample}.rds'),
                projection.file = glue('shiny/data.bak/{sample}/projection.csv'),
                dims.use = 1:dims
            )
            write_rds(object,
                      glue('shiny/data/{sample.parent}/{sample}.rds'),
                      compress = 'gz')
        }
    }
}
